### ISSUE TITLE
How to propagate parent state changes into ExpoGraphics.View component

### ISSUE THREAD

**Issue by jmkovachi** [expo/expo-graphics#1]
I am making an AR navigation app and I would like to send updates of state information from the parent component so I can transform objects appropriately with ExpoGraphics. Let's say a variable _magHeading_ is a field in the state of the main component in App.js. This variable updates the direction of the device every time the device moves. How do I access this information with the ExpoGraphics render function?

```
   onRender = delta => {
       
    this.cube.rotation.z += .4;
    this.cube.rotation.y += .1;
    var heading = this.state.magHeading;
    var angle = this.directions.convertToRotation(this.state.latitude, this.state.longitude, 34.04456, -84.498465, heading);
    var a = new THREE.Euler( 0, 6.28 - this.directions._toRad(angle), 0, 'XYZ' );
    this.dir = new THREE.Vector3( 0, 0, -3 );
    this.dir.applyEuler(a);
    this.dir.normalize();
    this.arrowHelper.setDirection(this.dir);

    this.renderer.render(this.scene, this.camera);
  };
```

For example, how would I make sure that this.state.magHeading is being updated correctly in this code sample? Am I doing this wrong?

**Comment by EvanBacon** [comment]
It's best to avoid using `state` for frame-by-frame updates like this. State is reactive and does a lot of work behind the scenes. If you don't need the React UI to update then just simply set regular variables
