### ISSUE TITLE
Don't work with expo v31 on Android

### ISSUE THREAD

**Issue by jacky-ttt** [expo/expo-graphics#14]
I found that expo-graphics does not work with the latest expo sdk v31 on Android. 
It will throw error:
```
undefined is not an object (evaluating'_expo.AR.TrackingConfigurations.World')
```

After days of research, I finally be able to make it work with sdk v28. 
Here is the working example. 
[https://github.com/jacky-ttt/Expo-graphics-Simple-Example](https://github.com/jacky-ttt/Expo-graphics-Simple-Example)

You can check out `sdk_31` branch to experience the error.

**Comment by Tino-F** [comment]
I'm getting this exact same error message in XCode 10. All I did was copy and paste the code from https://github.com/expo/expo-three#ar into my App.js file and it's giving me this error

**Comment by voanhtuan318** [comment]
jackTT how to move expo sdk 31 to sdk 28 , please help me.

**Comment by jacky-ttt** [comment]
@voanhtuan318 
You can follow the instructions stated here:
[https://docs.expo.io/versions/v31.0.0/workflow/upgrading-expo-sdk-walkthrough#sdk-28](https://docs.expo.io/versions/v31.0.0/workflow/upgrading-expo-sdk-walkthrough#sdk-28) 

1. app.json, change sdkVersion to "28.0.0"
2. In package.json, change these dependencies:
```
{
  "react-native": "https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz",
  "expo": "^28.0.0",
  "react": "16.3.1"
}
```
3. Delete your project’s node_modules directory and run npm install again

**Comment by voanhtuan318** [comment]
how to test verson sdk expo ,thank you.

**Comment by jacky-ttt** [comment]
@voanhtuan318 
You mean you want to find out the version of expo sdk you are using?
or
You mean how to make sure expo v28 is working with expo-graphics?

**Comment by voanhtuan318** [comment]
![48391490_500304807158318_339283887895085056_n](https://user-images.githubusercontent.com/44761312/50264607-fd4a2b00-044d-11e9-8d5d-9d4d70639e62.jpg)
after npm install I encountered this bug how to fix it,thanks you.

**Comment by jacky-ttt** [comment]
I think you should remove package-lock.json and node_module, then run npm install again. See if it helps.

**Comment by voanhtuan318** [comment]
![image](https://user-images.githubusercontent.com/44761312/50264984-e0165c00-044f-11e9-87ae-a5bb0688715f.png)
I don't have package-lock.json in your project .

**Comment by voanhtuan318** [comment]
![image](https://user-images.githubusercontent.com/44761312/50265888-16ee7100-0454-11e9-8a58-955b5cc986e0.png)
Here is it,thanks you

**Comment by jacky-ttt** [comment]
@voanhtuan318 
You should use expo-graphic v1.0.0-alpha.1 to make it work with expo v28. 
The latest version of expo-graphic v1.0.0-alpha.6 somehow has a Babel package conflict with expo v28. 

Please check out my repo for reference. 
[https://github.com/jacky-ttt/Expo-graphics-Simple-Example](https://github.com/jacky-ttt/Expo-graphics-Simple-Example)

**Comment by voanhtuan318** [comment]
How to install expo-graphic v1.0.0-alpha.1 @jacky-ttt ,thanks

**Comment by jacky-ttt** [comment]
@voanhtuan318 
There is two ways to do this. 
1. in your package.json, change to "expo-graphics": "1.0.0-alpha.1". then run `npm insall` again
2. run `npm install expo-graphics@1.0.0-alpha.1 --save`

**Comment by voanhtuan318** [comment]
Thank you very much for taking the time to help me, @jacky-ttt

**Comment by jacky-ttt** [comment]
@voanhtuan318 
For the warning in console, just ignore. It will still work. 

For the error on the screen. 
From my example project, I use  `arTrackingConfiguration={"AR.TrackingConfigurations.World"}` to bypass the error. It is for not using ARkit. 
```
<GraphicsView
  style={{ flex: 1 }}
  onContextCreate={this.onContextCreate}
  onRender={this.onRender}
  onResize={this.onResize}
  isArEnabled={false}
  isArRunningStateEnabled={false}
  isArCameraStateEnabled={false}
  arTrackingConfiguration={"AR.TrackingConfigurations.World"}
/>
```

**Comment by voanhtuan318** [comment]
thanks you very much, @jacky-ttt

**Comment by voanhtuan318** [comment]
Can't you help me project for load model three expo AR,thank you, @jacky-ttt

**Comment by jacky-ttt** [comment]
@voanhtuan318 I don't have an iphone, so I don't know how to use expo AR. 
You can take this repo, [expo-three-demo](https://github.com/EvanBacon/expo-three-demo) and [expo-three](https://github.com/expo/expo-three/tree/master/example/screens/Loaders) as reference.
