### ISSUE TITLE
GraphicsView will not render inside of a View component

### ISSUE THREAD

**Issue by JuicyPasta** [expo/expo-graphics#19]
GraphicsView works just fine as long as its the highest level view component. 

I find this strange because the GraphicsView is already just a GLView wrapped inside a View.  So you wouldn't expect another View to cause problems. 

This works!!
```
return ( <GridComponent/> )
```

This does not :(
```
return ( <View>
                <GridComponent/>
            </View>)
```

**Comment by JuicyPasta** [comment]
This solved my problem (below). It probably makes sense to make this the default style since nothing renders otherwise. 

```
                <GraphicsView
                    onContextCreate={this.onContextCreate}
                    onRender={this.onRender}
                    onResize={this.onResize}
                    onShouldReloadContext={this.onShouldReloadContext}
                    style={styles.container}
                />
        );

.....

const styles = StyleSheet.create({
    container: {
        alignItems: 'stretch',
        width: "100%",
        height: "100%"
    }
}
```

**Comment by murat-mehmet** [comment]
I am really lucky right now that I had the exact same problem and a solution was posted only 3 days ago. Thanks captain!

**Comment by jbrennan094** [comment]
Thanks @JuicyPasta that solved it!

Similar to the [ScrollView](https://facebook.github.io/react-native/docs/scrollview#docsNav) component it seems this component 

> must have a bounded height in order to work, since they contain unbounded-height children into a bounded container

> Forgetting to transfer {flex: 1} down the view stack can lead to errors here, which the element inspector makes quick to debug.

``` 
   return (
      <View style={{backgroundColor: 'blue', flex: 1}}>
        <GraphicsView
          onContextCreate={this.onContextCreate}
          onRender={this.onRender}
          style={{alignItems: 'stretch', flex:1}}
        />
      </View>
    );
```

Something like this should do the job.
