### ISSUE TITLE
hello, when should I use ExpoGraphics.View and when should I use Expo.GLView?

### ISSUE THREAD

**Issue by NippleTerminator** [expo/expo-graphics#3]
as titled,

Thanks!

**Comment by EvanBacon** [comment]
Hello Mr(s?). Terminator.

Graphics View extends GLView, you should use GLView when doing things closer to the metal. 
ExpoGraphics also provides a simpler interface for new users to jump into. 
For example, when setting up the timer [you do this](https://github.com/expo/expo-graphics/blob/d0ca8695d2531e1cf2d34adb43282d480fdd4e16/lib/View/index.native.js#L165-L179) and it can be a pain to do each time. 

I've also added views to make profiling ARKit simpler. In summation ExpoGraphics is like rails for a tool that is rails to native development. 😁
