### ISSUE TITLE
undefined is not an object (evaluating '_expo.AR.TrackingStateReasons.')

### ISSUE THREAD

**Issue by brianjckim** [expo/expo-graphics#6]
I'm trying to put together an AR drawing app. I started with create-react-native-app and added some components. I'm now trying to get the camera view to render, and I get the error below when I try to build it. I'm using expo, expo-three, three, and react native. I can't find anything on it online. Thanks!

![38880942_273323743461488_6744785017794199552_n](https://user-images.githubusercontent.com/29084277/43993587-ac658038-9d5d-11e8-8dc1-ee4447785810.png)

**Comment by rockmandash** [comment]
Same here, here is my code.
```javascript
import React from 'react';
import { View } from 'expo-graphics';

export default class App extends React.Component {
  render() {
    return null;
  }
}
```
As you can see, just importing the library will cause this error to happen.

**Comment by ronforbes** [comment]
Hey there. Just encountered the same issue and spent an embarrassing amount of time trying to solve it. Finally, updating to Expo 28 resolved the error.

Update instructions are here: https://blog.expo.io/expo-sdk-v28-0-0-is-now-available-f30e8253b530

**Comment by rockmandash** [comment]
I found that expo AR only meant to be work in iOS.
So if you are android, it might not be available.

**Comment by EvanBacon** [comment]
embarrassed, sorry peeps. FIxed now 😓 `alpha.5`

**Comment by KateMhq** [comment]
I've just set up a new AR project using [this guide](https://medium.com/@ericmorgan1/making-an-augmented-reality-app-with-react-native-expo-and-google-poly-d2acad175a7b)

Even with the most basic setup, identical the one @brianjckim listed above, I get the same redbox error wherever expo-graphics refers to `AR.TrackingConfigurations`. After some digging, I discovered that within expo, the object is called `AR.TrackingConfiguration` - singular, not plural. The same is true for `AR.TrackingStateReason(s)`.

By changing the expo-graphics source in my project's node_modules folder to use these singular names, my app launches and runs as expected.

Is there a good reason for this, or can I raise a pull request to change expo-graphics to use the singular AR object names?

**Comment by isychev** [comment]
Hotfix
```js
import * as Expo from 'expo';
Expo.AR.TrackingConfigurations = Expo.AR.TrackingConfiguration;
import ExpoTHREE, { three } from 'expo-three';
```

**Comment by demifire** [comment]
@KateMhq, is this still working for you? I did what you said and got past the errors, however the camera won't "open" 

I'm not too sure if I'm missing something. 

Any help is appreciated! Thanks

**Comment by Tino-F** [comment]
> I've just set up a new AR project using [this guide](https://medium.com/@ericmorgan1/making-an-augmented-reality-app-with-react-native-expo-and-google-poly-d2acad175a7b)
> 
> Even with the most basic setup, identical the one @brianjckim listed above, I get the same redbox error wherever expo-graphics refers to `AR.TrackingConfigurations`. After some digging, I discovered that within expo, the object is called `AR.TrackingConfiguration` - singular, not plural. The same is true for `AR.TrackingStateReason(s)`.
> 
> By changing the expo-graphics source in my project's node_modules folder to use these singular names, my app launches and runs as expected.
> 
> Is there a good reason for this, or can I raise a pull request to change expo-graphics to use the singular AR object names?

I had to modify ./node_modules/expo-graphics/lib/ARCameraState.js & ./node_modules/expo-graphics/View/index.native.js to use the singular names. I stopped getting error messages, but the camera won't open for me as well. I'm getting a warning that I think has something to do with it:

```
[Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_expo.AR.PlaneDetectionTypes.Horizontal')]
* App.js:27:48 in onContextCreate
- node_modules/expo-graphics/lib/View/index.native.js:185:25 in _callee$
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:44 in tryCatch
- ... 14 more stack frames from framework internals
```

**Comment by KateMhq** [comment]
Dear Tino,
Thanks for your email.
We have also noticed the naming difference in the Expo package. Therefore, a patch package is available to fix the problem (it should be available on the repository).
In the meantime, please feel free to create a pull request and I will look into that.
Thanks,Kate

		
		

		Get Outlook for iOS
	





On Tue, Dec 11, 2018 at 10:20 AM +0800, "Tino Fileccia" <notifications@github.com> wrote:













I've just set up a new AR project using this guide


Even with the most basic setup, identical the one @brianjckim listed above, I get the same redbox error wherever expo-graphics refers to AR.TrackingConfigurations. After some digging, I discovered that within expo, the object is called AR.TrackingConfiguration - singular, not plural. The same is true for AR.TrackingStateReason(s).


By changing the expo-graphics source in my project's node_modules folder to use these singular names, my app launches and runs as expected.


Is there a good reason for this, or can I raise a pull request to change expo-graphics to use the singular AR object names?



I had to modify ./node_modules/expo-graphics/lib/ARCameraState.js & ./node_modules/expo-graphics/View/index.native.js to use the singular names. I stopped getting error messages, but the camera won't open for me as well. I'm getting a warning that I think has something to do with it:
[Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_expo.AR.PlaneDetectionTypes.Horizontal')]
* App.js:27:48 in onContextCreate
- node_modules/expo-graphics/lib/View/index.native.js:185:25 in _callee$
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:44 in tryCatch
- ... 14 more stack frames from framework internals
